// src/styles/dashboardStyles.js

export const dashboardStyles = {
  toastWrap: {
    position: "fixed",
    top: 18,
    right: 18,
    width: 360,
    maxWidth: "calc(100vw - 36px)",
    padding: "12px 12px",
    borderRadius: 16,
    zIndex: 2500,
    boxShadow: "0 18px 40px rgba(0,0,0,0.18)",
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
  },
  toastError: { background: "#111827", color: "white", border: "1px solid rgba(239,68,68,0.35)" },
  toastSuccess: { background: "#111827", color: "white", border: "1px solid rgba(16,185,129,0.35)" },
  toastClose: {
    border: "none",
    background: "transparent",
    color: "white",
    cursor: "pointer",
    fontWeight: 900,
    padding: "2px 6px",
    borderRadius: 8,
  },

  whiteInput: {
    width: "100%",
    padding: "12px",
    borderRadius: 12,
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    marginBottom: 10,
    outline: "none",
    fontSize: 14,
    color: "#111827",
    boxSizing: "border-box",
  },
  whiteGroupInput: {
    flex: 1,
    padding: "12px",
    borderRadius: "12px 0 0 12px",
    border: "1px solid #e5e7eb",
    background: "#ffffff",
    fontSize: 14,
    color: "#111827",
    outline: "none",
    boxSizing: "border-box",
  },

  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    background: "rgba(17,24,39,0.35)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    padding: 16,
  },
  modalCard: {
    background: "white",
    padding: 30,
    borderRadius: 24,
    textAlign: "center",
    width: "100%",
    maxWidth: 420,
    boxShadow: "0 30px 80px rgba(0,0,0,0.25)",
  },

  modalBtnRow: { display: "flex", gap: 12 },

  // ✅ FIXED: Cancel button text color added
  modalCancelBtn: {
    flex: 1,
    padding: 12,
    minHeight: 44,
    borderRadius: 12,
    border: "1px solid #e5e7eb",
    background: "white",
    color: "#111827", // 🔥 THIS FIXES WHITE-ON-WHITE
    cursor: "pointer",
    fontWeight: 800,
  },

  modalConfirmBtn: {
    flex: 1,
    padding: 12,
    minHeight: 44,
    borderRadius: 12,
    border: "none",
    background: "#111827",
    color: "white",
    cursor: "pointer",
    fontWeight: 800,
  },

  pageWrapper: {
    display: "flex",
    gap: 30,
    maxWidth: 1100,
    margin: "0 auto",
    padding: "20px",
  },
  leftColumn: { flex: "0 0 350px", display: "flex", flexDirection: "column", gap: 20 },
  rightColumn: { flex: 1, background: "white", padding: 25, borderRadius: 24, border: "1px solid #f3f4f6" },

  balanceCard: { background: "#111827", color: "white", padding: "28px", borderRadius: 24 },
  balanceText: {
  fontSize: 38,
  fontWeight: 900,
  margin: "6px 0",
  whiteSpace: "nowrap",
  overflow: "hidden",
  textOverflow: "ellipsis",
},

  card: { background: "white", padding: 20, borderRadius: 24, border: "1px solid #f3f4f6" },
  cardTitle: { margin: "0 0 15px 0", fontSize: 16, fontWeight: 800 },

  headerSection: { paddingBottom: 5 },
  inputGroup: { display: "flex", marginBottom: 10 },

  sendBtn: {
    width: "100%",
    padding: 13,
    minHeight: 46,
    borderRadius: 12,
    background: "#2563eb",
    color: "white",
    border: "none",
    fontWeight: 700,
    cursor: "pointer",
  },
  addBtn: {
    padding: "0 18px",
    minHeight: 46,
    borderRadius: "0 12px 12px 0",
    background: "#10b981",
    color: "white",
    border: "none",
    cursor: "pointer",
    fontWeight: 700,
  },
  takeBtn: {
    padding: "0 18px",
    minHeight: 46,
    borderRadius: "0 12px 12px 0",
    background: "#111827",
    color: "white",
    border: "none",
    cursor: "pointer",
    fontWeight: 700,
  },

  listHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 20 },
  filterLinks: { display: "flex", gap: 12 },
  filterItem: { fontSize: 11, fontWeight: 800, cursor: "pointer", paddingBottom: 8 },

  listContainer: { display: "flex", flexDirection: "column" },
  txRow: { display: "flex", alignItems: "center", padding: "14px 0", borderBottom: "1px solid #f9fafb" },
  iconBox: {
    width: 38,
    height: 38,
    borderRadius: 10,
    background: "#f3f4f6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  txTitle: { fontWeight: 700, fontSize: 13, color: "#111827" },
  txDetailsRow: { display: "flex", alignItems: "center", gap: 8, marginTop: 2 },
  txDateText: { fontSize: 11, color: "#9ca3af" },
  statusBadge: {
    fontSize: 9,
    fontWeight: 700,
    textTransform: "uppercase",
    padding: "2px 6px",
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  statusDot: { width: 5, height: 5, borderRadius: "50%" },
};
